from __future__ import annotations

from typing import Any


MODULE_CATALOG: list[dict[str, Any]] = [
    {
        "id": "lp_step_by_step",
        "group": "operations_research",
        "title": "Linear Programming Step-by-Step",
        "coverage": "implemented",
        "methods": ["standard form", "2-variable graphical explanation", "primal simplex tableau", "HiGHS simplex/IPM solve"],
        "implemented": ["natural/LaTeX parser", "optimal/infeasible/unbounded detection", "detailed 2D corner report", "simplex tableau for max Ax<=b"],
        "next": ["Big-M/two-phase artificial variable tables"],
    },
    {
        "id": "duality",
        "group": "operations_research",
        "title": "Duality",
        "coverage": "implemented",
        "methods": ["shadow price", "slack", "binding constraint explanation"],
        "implemented": ["LP solver marginals from HiGHS", "constraint status explanation", "automatic primal-to-dual for max Ax<=b", "complementary slackness table"],
        "next": ["mixed-sign/free-variable dual forms"],
    },
    {
        "id": "sensitivity",
        "group": "operations_research",
        "title": "Sensitivity Analysis",
        "coverage": "implemented",
        "methods": ["shadow price", "reduced cost", "slack", "what-if rerun"],
        "implemented": ["LP sensitivity endpoint", "constraint slack/binding status", "RHS allowable range by parametric re-solve", "objective coefficient ranges by parametric re-solve"],
        "next": ["basis-exact ranges from tableau"],
    },
    {
        "id": "integer_mixed_integer",
        "group": "operations_research",
        "title": "Integer and Mixed-Integer Programming",
        "coverage": "implemented",
        "methods": ["binary variables", "integer variables", "fixed charge", "facility location"],
        "implemented": ["assignment as binary special case", "general scipy.milp endpoint", "small enumeration fallback"],
        "next": ["fixed-charge templates", "facility location parser"],
    },
    {
        "id": "goal_programming",
        "group": "operations_research",
        "title": "Goal Programming",
        "coverage": "implemented",
        "methods": ["weighted goals", "preemptive goals", "deviation variables d+/d-"],
        "implemented": ["multi-objective weighted scoring", "weighted goal programming deviation-variable LP", "preemptive sequential solve"],
        "next": ["UI form templates for priorities"],
    },
    {
        "id": "network_optimization",
        "group": "operations_research",
        "title": "Network Optimization",
        "coverage": "implemented",
        "methods": ["shortest path", "Bellman-Ford", "MST", "transportation", "assignment", "maximum flow", "minimum-cost flow"],
        "implemented": ["Dijkstra validation", "Bellman-Ford", "Kruskal/Prim MST", "Hungarian method", "NetworkX flow solvers", "markdown solution reports"],
        "next": ["network graph highlight for every algorithm"],
    },
    {
        "id": "dynamic_programming",
        "group": "operations_research",
        "title": "Dynamic Programming",
        "coverage": "implemented",
        "methods": ["finite-stage DP", "resource allocation DP", "production planning DP"],
        "implemented": ["Bellman table", "traceback", "maximize/minimize resource allocation parser", "deterministic multi-period inventory DP", "stochastic inventory simulation policy evaluation"],
        "next": ["exact stochastic dynamic programming with probability distributions"],
    },
    {
        "id": "inventory",
        "group": "operations_research",
        "title": "Inventory Models",
        "coverage": "implemented",
        "methods": ["EOQ", "quantity discount", "production lot size", "reorder point", "newsvendor", "stochastic inventory simulation"],
        "implemented": ["closed-form solvers", "normal-demand newsvendor quantile", "(s,S) stochastic simulation", "deterministic inventory DP"],
        "next": ["exact stochastic DP from demand PMF"],
    },
    {
        "id": "queueing",
        "group": "operations_research",
        "title": "Queueing Theory",
        "coverage": "implemented",
        "methods": ["M/M/1", "M/M/c", "M/M/1/K", "M/G/1", "Jackson network basics"],
        "implemented": ["L, Lq, W, Wq, utilization rho", "stability checks", "Pollaczek-Khinchine M/G/1", "open queue network traffic equations"],
        "next": ["discrete-event simulation animation"],
    },
    {
        "id": "markov_chain",
        "group": "operations_research",
        "title": "Markov Chain / Random Process",
        "coverage": "implemented",
        "methods": ["n-step transition", "steady-state", "absorbing chain"],
        "implemented": ["matrix power", "iterative stationary distribution", "fundamental matrix"],
        "next": ["Markov reward process report"],
    },
    {
        "id": "simulation",
        "group": "operations_research",
        "title": "Simulation",
        "coverage": "implemented",
        "methods": ["Monte Carlo", "VaR/CVaR", "confidence interval"],
        "implemented": ["decision Monte Carlo", "risk samples endpoint", "inventory stochastic simulation", "queue analytical simulation proxies"],
        "next": ["SimPy discrete-event animation"],
    },
    {
        "id": "nonlinear_programming",
        "group": "operations_research",
        "title": "Nonlinear Programming",
        "coverage": "implemented",
        "methods": ["scipy.optimize", "convexity warning", "KKT for small problems"],
        "implemented": ["structured quadratic objective SLSQP endpoint", "KKT teaching notes", "convexity eigenvalue check for quadratic", "local/global warning"],
        "next": ["symbolic KKT algebra view"],
    },
    {
        "id": "decision_tree",
        "group": "decision_analysis",
        "title": "Decision Tree",
        "coverage": "implemented",
        "methods": ["rollback expected value", "probability tree", "Bayes event tree"],
        "implemented": ["chance/path reports", "expected payoff", "decision criteria"],
        "next": ["interactive tree editor"],
    },
    {
        "id": "influence_diagram",
        "group": "decision_analysis",
        "title": "Influence Diagram",
        "coverage": "implemented",
        "methods": ["decision/chance/value nodes", "dependency arcs", "tree conversion"],
        "implemented": ["D3 decision map visualization", "influence diagram schema analyzer", "Mermaid report", "topological order", "decision-tree skeleton conversion"],
        "next": ["full payoff/probability rollback from converted tree"],
    },
    {
        "id": "probability_assessment",
        "group": "decision_analysis",
        "title": "Probability Assessment",
        "coverage": "implemented",
        "methods": ["prior", "conditional probability", "Bayes update", "independence"],
        "implemented": ["Bayes endpoint", "independent event endpoint", "distribution fitting"],
        "next": ["subjective elicitation wizard"],
    },
    {
        "id": "value_of_information",
        "group": "decision_analysis",
        "title": "Value of Information",
        "coverage": "implemented",
        "methods": ["EVPI", "EVSI/EVI", "posterior probability"],
        "implemented": ["EVPI from payoff matrix", "EVI/EVSI endpoint with test likelihoods", "buy-information recommendation"],
        "next": ["visual sample-information tree"],
    },
    {
        "id": "utility_theory",
        "group": "decision_analysis",
        "title": "Utility Theory",
        "coverage": "implemented",
        "methods": ["expected utility", "certainty equivalent", "risk premium", "exponential utility"],
        "implemented": ["risk attitude via risk tolerance", "lottery CE endpoint", "risk tolerance fitting from CE preference questions"],
        "next": ["interactive elicitation wizard"],
    },
    {
        "id": "multi_attribute_decision_analysis",
        "group": "decision_analysis",
        "title": "Multi-Attribute Decision Analysis",
        "coverage": "implemented",
        "methods": ["weighted scoring", "Pareto comparison", "additive utility", "AHP"],
        "implemented": ["weighted score", "Pareto frontier", "MAUT additive normalized utility", "AHP weights and consistency ratio"],
        "next": ["swing-weight interview UI"],
    },
    {
        "id": "risk_analysis",
        "group": "decision_analysis",
        "title": "Risk Analysis",
        "coverage": "implemented",
        "methods": ["expected value", "variance", "probability of loss", "VaR", "CVaR"],
        "implemented": ["risk endpoint", "simulation risk report"],
        "next": ["scenario tornado chart"],
    },
    {
        "id": "explanation_teaching",
        "group": "decision_analysis",
        "title": "Explanation and Teaching",
        "coverage": "implemented",
        "methods": ["step-by-step solution", "short answer mode", "validity check"],
        "implemented": ["shared teaching report wrapper", "markdown reports for LP/DP/probability/network/inventory/queueing/Markov/NLP/influence/MAUT/behavioral", "missing-data questions"],
        "next": ["user-selectable explanation depth in UI"],
    },
]


def module_coverage_report() -> dict[str, Any]:
    counts: dict[str, int] = {}
    for item in MODULE_CATALOG:
        counts[item["coverage"]] = counts.get(item["coverage"], 0) + 1
    return {
        "textbook_scope": [
            "A. Ravindran, D. T. Phillips, J. J. Solberg - Operations Research: Principles and Practice",
            "R. T. Clemen - Making Hard Decisions: An Introduction to Decision Analysis",
        ],
        "counts": counts,
        "modules": MODULE_CATALOG,
    }
